FROM ruby:2.5.0
ENV LANG C.UTF-8
ENV APP_ROOT /thx
WORKDIR $APP_ROOT
RUN \
    apt-get update -qq && \
    apt-get install -y build-essential nodejs cron
COPY Gemfile $APP_ROOT
COPY Gemfile.lock $APP_ROOT
RUN \
  gem install bundler && \
  bundle config --global build.nokogiri --use-system-libraries && \
  bundle install
COPY . $APP_ROOT

ENV RAILS_ENV test

EXPOSE  3000

