apiVersion: batch/v1
kind: Job
metadata:
  name: first-deploy-tasks
spec:
  template:
    metadata:
      name: first-deploy-tasks
      labels:
        name: first-deploy-tasks
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
      restartPolicy: Never
      containers:
        - name: first-deploy-tasks-runner
          image: $IMAGE
          command: ["./script/first_deploy_task.sh"]
          resources:
            requests:
              cpu: 50m
          env:
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: secret_key_base
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: mysql_database
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: mysql_user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: mysql_password
            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: thx-slack-secret
                  key: slack_webhook_url
            - name: SLACK_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: thx-slack-secret
                  key: slack_api_token
            - name: REPORT_USER_ID
              valueFrom:
                secretKeyRef:
                  name: thx-slack-secret
                  key: report_user_id