apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
  labels:
    name: web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: web
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
      containers:
        - name: web
          image: asia.gcr.io/techperk-201607/thx_app_prod:1.9.7
          resources:
            requests:
              cpu: 200m
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /_health
              port: 3000
            initialDelaySeconds: 120
            timeoutSeconds: 1
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /_health
              port: 3000
            initialDelaySeconds: 120
            timeoutSeconds: 1
            periodSeconds: 60
          env:
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: secret_key_base
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: mysql_database
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: mysql_user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: mysql_password
            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: thx-slack-secret
                  key: slack_webhook_url
            - name: SLACK_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: thx-slack-secret
                  key: slack_api_token
            - name: REPORT_USER_ID
              valueFrom:
                secretKeyRef:
                  name: thx-slack-secret
                  key: report_user_id
